### ISSUE TITLE
Deprecated error object key

### ISSUE THREAD

**Issue by suraneti** [SvanBoxel/delete-merged-branch#239]
```
07:29:55.916Z  INFO probot: Loaded delete-merged-branch GitHub Application
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:15092:17)
    at Object.Logger.stdSerializers.err (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:2735[6](https://github.com/tokenx-finance/tkx-oracle-service/runs/8151391728?check_suite_focus=true#step:2:7):19)
    at mkRecord (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:2[7](https://github.com/tokenx-finance/tkx-oracle-service/runs/8151391728?check_suite_focus=true#step:2:8)150:35)
    at Logger.warn (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:27252:1[9](https://github.com/tokenx-finance/tkx-oracle-service/runs/8151391728?check_suite_focus=true#step:2:10))
    at module.exports (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:64:17)
```

**Comment by Adinath-Dukare-382** [comment]
@suraneti  What's the solution for the above error? How you resolved it?

**Comment by adamatti** [comment]
Same issue here
